/* ============================================================
   D3-3: データ確認 UI
   Summary=集計、Detail=掘り下げをそれぞれ共通派生レイヤーから取得。
   UIからSOURCEを直接判定・解決・保存しない。
============================================================ */
'use strict';
(function(){
  if(window.__DATA_VERIFICATION_UI_LOADED_20260817__) return;
  window.__DATA_VERIFICATION_UI_LOADED_20260817__=true;
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const n=v=>Number(v||0).toLocaleString('ja-JP');
  const yen=v=>`${Number(v||0).toLocaleString('ja-JP')}円`;
  const ymLabel=ym=>/^\d{6}$/.test(String(ym||''))?`${String(ym).slice(0,4)}年${Number(String(ym).slice(4,6))}月`:'対象月未選択';
  const statusLabel={OK:'正常',PROVISIONAL:'確認途中',PARTIAL:'要確認',CONFLICT:'不一致',NO_DATA:'データなし'};
  let detailMode='WORKER_LABELS';

  function allYms(){const set=new Set(),add=x=>{const y=String(x?.ym||'').replace(/\D/g,'').slice(0,6);if(/^\d{6}$/.test(y))set.add(y)};(STATE.datasets||[]).forEach(add);(STATE.workerCsvData||[]).forEach(add);(STATE.productAddressData||[]).forEach(add);(STATE.routeData||[]).forEach(add);return [...set].sort();}
  function selectedYm(){const el=document.getElementById('data-verification-ym');return el?.value||allYms().at(-1)||'';}
  function sourceStatus(ym){const ds=(STATE.datasets||[]).filter(x=>x?.ym===ym&&x.source!=='history'),confirmed=ds.some(x=>(x.type||'confirmed')==='confirmed'),worker=(STATE.workerCsvData||[]).filter(x=>x?.ym===ym),product=(STATE.productAddressData||[]).filter(x=>x?.ym===ym),route=(STATE.routeData||[]).filter(x=>x?.ym===ym),hasRoute=route.some(x=>Array.isArray(x.routes)&&x.routes.length),hasPayment=route.some(x=>Array.isArray(x.headPayments)&&x.headPayments.length);return {PL_ACTUAL:{present:confirmed,document_states:confirmed?['CONFIRMED']:[],file_count:confirmed?1:0},WORKER_SALES:{present:worker.length>0,file_count:worker.length},SHIPPER_AREA:{present:product.length>0,file_count:product.length},DELIVERY_LIST:{present:hasRoute,file_count:hasRoute?route.length:0},ROUTE_PAYMENT:{present:hasPayment,file_count:hasPayment?route.length:0}};}
  function buildData(ym){if(!window.CANONICAL_BUILDER||!window.DATA_VERIFICATION_SUMMARY)return null;const routeData=(STATE.routeData||[]).filter(x=>x?.ym===ym),snapshot=CANONICAL_BUILDER.buildSnapshot({routeData});return {snapshot,summary:DATA_VERIFICATION_SUMMARY.build({center_id:window.CENTER?.id||null,year_month:ym,canonical_snapshot:snapshot,source_status:sourceStatus(ym),accounting_facts:[],accounting_reconciliations:[]}),detail:window.DATA_VERIFICATION_DETAIL?.build({center_id:window.CENTER?.id||null,year_month:ym,canonical_snapshot:snapshot,worker_csv_data:STATE.workerCsvData||[]})||null};}
  function buildSummary(ym){return buildData(ym)?.summary||null;}
  function sourceCards(s){const names={PL_ACTUAL:'月次収支（確定）',WORKER_SALES:'作業者別売上明細',SHIPPER_AREA:'荷主別配送エリア物量',DELIVERY_LIST:'配達持出予定リスト',ROUTE_PAYMENT:'配達ヘッド傭車料確認'};return Object.entries(names).map(([k,label])=>{const x=s.source_status[k]||{};return `<div class="dv-source ${x.present?'is-present':'is-missing'}"><div class="dv-source-mark">${x.present?'✓':'—'}</div><div><div class="dv-source-name">${esc(label)}</div><div class="dv-source-meta">${x.present?`登録あり${x.document_states?.length?' / '+x.document_states.join(', '):''}`:'未登録'}</div></div></div>`}).join('');}
  function detailTable(d){if(!d)return '<div class="dv-empty-inline">詳細基盤を読み込めません。</div>';
    if(detailMode==='WORKER_LABELS'){const rows=d.legacy_worker_labels||[];return `<div class="dv-detail-note">現在の保存済み作業者CSVから確認できる帰属主体表記です。ここでは人物・会社等を自動確定しません。</div><table class="dv-table"><thead><tr><th>作業者欄の原表記</th><th>原票件数</th><th>既知金額</th><th>状態</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${esc(x.source_label)}</td><td>${n(x.slip_count)}</td><td>${yen(x.amount)}</td><td><span class="dv-pill">未評価</span></td></tr>`).join('')||'<tr><td colspan="4">対象データなし</td></tr>'}</tbody></table>`;}
    if(detailMode==='HEADLESS'){const rows=d.headless_observations||[];return `<div class="dv-detail-note">HEADなしは直接完了等の正常ケースを含むため、異常とは判定しません。</div><table class="dv-table"><thead><tr><th>原票NO</th><th>状態</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${esc(x.slip_no||'—')}</td><td><span class="dv-pill is-observation">観測</span></td></tr>`).join('')||'<tr><td colspan="2">対象データなし</td></tr>'}</tbody></table>`;}
    if(detailMode==='VALUE'){const rows=d.value_attention||[];return `<div class="dv-detail-note">0円ではなく、金額を確定できないレコードだけを表示します。</div><table class="dv-table"><thead><tr><th>対象</th><th>原票NO</th><th>HEAD</th><th>状態</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${esc(x.entity)}</td><td>${esc(x.slip_no||'—')}</td><td>${esc(x.head_no||'—')}</td><td><span class="dv-pill is-attention">${esc(x.status)}</span></td></tr>`).join('')||'<tr><td colspan="4">対象データなし</td></tr>'}</tbody></table>`;}
    const rows=d.reconciliation_observations||[];return `<div class="dv-detail-note">差異・片側SOURCEは正常ケースを含むため、観測情報として表示します。</div><table class="dv-table"><thead><tr><th>状態</th><th>左値</th><th>右値</th><th>差額</th></tr></thead><tbody>${rows.map(x=>`<tr><td><span class="dv-pill is-observation">${esc(x.status)}</span></td><td>${x.left_value==null?'—':yen(x.left_value)}</td><td>${x.right_value==null?'—':yen(x.right_value)}</td><td>${x.difference==null?'—':yen(x.difference)}</td></tr>`).join('')||'<tr><td colspan="4">対象データなし</td></tr>'}</tbody></table>`;}
  function setDetail(mode){detailMode=mode;render();}
  function render(){const host=document.getElementById('data-verification-root');if(!host)return;const ym=selectedYm(),yms=allYms(),sel=document.getElementById('data-verification-ym');if(sel){const keep=sel.value;sel.innerHTML=yms.map(y=>`<option value="${y}">${ymLabel(y)}</option>`).join('');sel.value=(keep&&yms.includes(keep))?keep:(ym||'');}if(!ym){host.innerHTML='<div class="dv-empty">確認できるデータがありません。先にデータ取込を行ってください。</div>';return;}const data=buildData(ym);if(!data){host.innerHTML='<div class="dv-empty">データ確認基盤を読み込めませんでした。</div>';return;}const s=data.summary,c=s.entity_counts||{},l=s.link_summary||{},i=s.issue_summary||{},o=s.observation_summary||{},v=s.value_summary||{};
    host.innerHTML=`<div class="dv-overview"><div><div class="dv-eyebrow">総合状態</div><div class="dv-status dv-${esc(s.overall_status)}">${esc(statusLabel[s.overall_status]||s.overall_status)}</div></div><div class="dv-overview-note">${esc(ymLabel(ym))} / ${esc(window.CENTER?.name||'')}</div></div>
    <div class="dv-section-title">必要資料</div><div class="dv-source-grid">${sourceCards(s)}</div>
    <div class="dv-section-title">連動状況</div><div class="dv-kpis"><div class="dv-kpi"><span>配送HEAD</span><strong>${n(c.DELIVERY_ROUTE)}</strong></div><div class="dv-kpi"><span>原票</span><strong>${n(c.BUSINESS_SLIP)}</strong></div><div class="dv-kpi"><span>持出履歴</span><strong>${n(c.DELIVERY_ATTEMPT)}</strong></div><div class="dv-kpi"><span>HEADなし原票</span><strong>${n(l.slips_without_delivery_attempt)}</strong><small>正常ケースを含む</small></div></div>
    <div class="dv-two-col"><div class="card"><div class="card-header"><span class="card-title">要確認</span></div><div class="card-body dv-lines"><div><span>Subject不一致</span><b>${n(i.subject_conflict)}</b></div><div><span>Subject未照合</span><b>${n(i.subject_unmatched)}</b></div><div><span>未評価</span><b>${n(i.subject_not_evaluated)}</b></div><div><span>金額UNKNOWN</span><b>${n(i.unknown_value_count)}</b></div></div></div><div class="card"><div class="card-header"><span class="card-title">差異・観測</span></div><div class="card-body dv-lines"><div><span>SOURCE差異</span><b>${n(o.source_variance)}</b></div><div><span>片側SOURCE</span><b>${n(o.single_source)}</b></div><div><span>会計差異</span><b>${n(o.accounting_variance)}</b></div><div><span>会計のみ</span><b>${n(o.accounting_only)}</b></div><p>差異や片側SOURCEは正常な業務ケースを含むため、自動的にエラー扱いしません。</p></div></div></div>
    <div class="card"><div class="card-header"><span class="card-title">金額データ品質</span></div><div class="card-body"><div class="dv-value-grid"><div><span>売上・既知</span><b>${n(v.sales_amount?.known_value)}</b></div><div><span>売上・明示0円</span><b>${n(v.sales_amount?.known_zero)}</b></div><div><span>売上・UNKNOWN</span><b>${n(v.sales_amount?.unknown)}</b></div><div><span>傭車料・既知</span><b>${n(v.route_payment_amount?.known_value)}</b></div><div><span>傭車料・明示0円</span><b>${n(v.route_payment_amount?.known_zero)}</b></div><div><span>傭車料・UNKNOWN</span><b>${n(v.route_payment_amount?.unknown)}</b></div></div></div></div>
    <div class="card dv-detail-card"><div class="card-header"><span class="card-title">確認詳細</span><span class="dv-readonly">読取専用</span></div><div class="card-body"><div class="dv-tabs">${[['WORKER_LABELS','帰属主体表記'],['HEADLESS','HEADなし原票'],['VALUE','金額UNKNOWN'],['RECON','SOURCE差異']].map(([k,t])=>`<button type="button" class="dv-tab ${detailMode===k?'active':''}" onclick="DATA_VERIFICATION_UI.setDetail('${k}')">${t}</button>`).join('')}</div><div class="dv-detail-scroll">${detailTable(data.detail)}</div><div class="dv-footnote">D3-3では確認だけを行います。Masterへの紐付け・Alias登録・データ修正はまだ保存しません。</div></div></div>`;}
  window.DATA_VERIFICATION_UI=Object.freeze({render,buildSummary,setDetail});
})();
